import { CircuitDef } from '../types';

// Helper to generate transient simulation curves
function generateTransient(points: number, fn: (t: number) => { vin: number; vout: number }): {
  transientTime: number[];
  vin: number[];
  vout: number[];
} {
  const transientTime: number[] = [];
  const vin: number[] = [];
  const vout: number[] = [];
  for (let i = 0; i <= points; i++) {
    const t = (i / points) * 0.1; // 100ms window
    const val = fn(t);
    transientTime.push(parseFloat(t.toFixed(4)));
    vin.push(parseFloat(val.vin.toFixed(4)));
    vout.push(parseFloat(val.vout.toFixed(4)));
  }
  return { transientTime, vin, vout };
}

// Helper to generate Bode plot data (10 Hz to 100 kHz)
function generateBode(fc: number, order: number, dcGainDb: number): {
  freq: number[];
  gainDb: number[];
  phaseDeg: number[];
} {
  const freq: number[] = [];
  const gainDb: number[] = [];
  const phaseDeg: number[] = [];

  for (let logF = 0; logF <= 5; logF += 0.1) {
    const f = Math.pow(10, logF);
    freq.push(parseFloat(f.toFixed(1)));
    const ratio = f / fc;
    const gain = dcGainDb - 10 * order * Math.log10(1 + Math.pow(ratio, 2 * order));
    const phase = -order * (Math.atan(ratio) * (180 / Math.PI));
    gainDb.push(parseFloat(gain.toFixed(2)));
    phaseDeg.push(parseFloat(phase.toFixed(1)));
  }
  return { freq, gainDb, phaseDeg };
}

export const CIRCUITS_DATA: CircuitDef[] = [
  {
    id: 'ph_afe',
    title: '1. High-Impedance pH Sensor Analog Front-End',
    subsystem: 'Potentiometric Biosensor Interface (Wound Bed Alkalinization Tracking)',
    description:
      'Electro-chemical pH probe signal conditioner with >10^12 Ω input impedance, pA-range input bias current, 2nd-order Sallen-Key low-pass filter (fc ≈ 10 Hz), and baseline level-shifting to match the 0-3.3V ADC range of the ESP32.',
    principle:
      'The Nernst potential generated by the solid-state IrOx (Iridium Oxide) / Ag/AgCl reference electrode produces an open-circuit voltage: E = E0 - (2.303*R*T/F)*pH ≈ E0 - 59.16mV/pH at 25°C. Because the sensor source resistance exceeds 100 MΩ, an ultra-low bias current op-amp (LTC2050 / AD8605) buffers the signal without loading errors.',
    keySpecs: [
      'Input Bias Current: pA-range input bias current (prevents electrode charge depletion)',
      'Input Impedance: Zin > 10^12 Ω',
      'Signal Dynamic Range: pH 4.0 (-118 mV) to pH 10.0 (+236 mV)',
      'Output Voltage Range: 0.25V to 3.05V (Safe 0-3.3V ESP32 ADC window)',
      'Filter Topology: 2nd-Order Sallen-Key Low-Pass (fc ≈ 10 Hz)',
      '50/60 Hz Mains Rejection: > 45 dB attenuation',
    ],
    schematicSvgType: 'ph',
    netlistCir: `* HealSecure AI - High-Impedance pH Sensor Conditioning AFE
* SPICE Netlist for LTspice XVII / LTspice 24
.SUBCKT HEALSECURE_PH_AFE VDD VSS V_ELEC V_REF V_ADC_OUT

* High-Impedance Biosensor Buffer (U1A: LTC2050 / AD8605)
* Modeled with 100 MOhm source impedance and 50Hz hum pickup
R_SOURCE V_ELEC N_PROBE_IN 100MEG
C_CABLE  N_PROBE_IN 0 22p

* Buffer stage with pA-range input bias current
X_U1A N_PROBE_IN N_BUF_OUT N_BUF_OUT VDD VSS LTC2050
R_ISO N_BUF_OUT N_FILTER_IN 1k

* 2nd-Order Sallen-Key Low Pass Filter (fc ≈ 10 Hz)
R1 N_FILTER_IN N_SK1 160k
R2 N_SK1 N_U1B_IN 160k
C1 N_SK1 N_SK_OUT 140n
C2 N_U1B_IN 0 70n
X_U1B N_U1B_IN N_SK_OUT N_SK_OUT VDD VSS LTC2050

* Differential Level Shifter & Gain Stage (Maps -150mV..+250mV to 0.3V..3.0V)
* Vout = (V_sk - V_ref)*Gain + V_offset
R_GAIN1 N_SK_OUT N_SUM 33k
R_FB N_SUM V_ADC_OUT 150k
R_OFFSET V_REF N_SUM 100k
C_OUT V_ADC_OUT 0 10n

.MODEL D_ESD D(IS=1e-14 RS=5)
D_ESD_HI N_PROBE_IN VDD D_ESD
D_ESD_LO VSS N_PROBE_IN D_ESD

.ENDS HEALSECURE_PH_AFE

* Testbench Simulation Directives
V_DD VDD 0 DC 3.3
V_SS VSS 0 DC 0
V_REF V_REF 0 DC 1.65
* Simulated pH step from pH 6.5 (Normal) to pH 8.0 (Infection) + 50Hz noise
V_PH V_ELEC 0 PWL(0 0.03 0.02 0.03 0.05 -0.06 0.08 -0.06) SINE(0 0.02 50)
X1 VDD VSS V_ELEC V_REF V_ADC_OUT HEALSECURE_PH_AFE

.tran 0 0.1 0 1u
.ac dec 20 0.1 100k
.plot V(V_ADC_OUT) V(V_ELEC)
.backanno
.end`,
    ltspiceAsc: `Version 4
SHEET 1 1280 920
WIRE 120 180 60 180
WIRE 240 180 180 180
WIRE 320 180 240 180
WIRE 400 180 320 180
FLAG 60 260 0
FLAG 400 280 0
FLAG 1020 180 V_ADC_OUT
FLAG 60 180 V_ELEC
FLAG 120 40 VDD
FLAG 120 360 VSS
SYMBOL res 180 160 R90
WINDOW 0 0 56 VBottom 2
WINDOW 3 32 56 VTop 2
SYMATTR InstName R_SOURCE
SYMATTR Value 100MEG
SYMBOL Opamps\\\\LTC2050 360 200 R0
SYMATTR InstName U1A
SYMATTR Value LTC2050
SYMBOL res 520 160 R90
SYMATTR InstName R1_SK
SYMATTR Value 160k
SYMBOL res 680 160 R90
SYMATTR InstName R2_SK
SYMATTR Value 160k
SYMBOL cap 620 100 R0
SYMATTR InstName C1_SK
SYMATTR Value 140n
SYMBOL cap 740 220 R0
SYMATTR InstName C2_SK
SYMATTR Value 70n
SYMBOL Opamps\\\\LTC2050 820 200 R0
SYMATTR InstName U1B
SYMATTR Value LTC2050
TEXT 180 400 Left 2 !.tran 0 0.1 0 1u
TEXT 180 440 Left 2 !.ac dec 20 0.1 100k
TEXT 180 480 Left 2 ; HealSecure AI - pH Sensor AFE (pA-Range LTC2050 Buffer)`,
    designEquations: [
      {
        formula: 'E_{cell} = E_0 - \\frac{2.303 R T}{F} \\cdot \\text{pH}',
        explanation: 'Nernstian potentiometric electrode response yielding -59.16 mV per pH unit at 25°C.',
      },
      {
        formula: 'f_c = \\frac{1}{2\\pi \\sqrt{R_1 R_2 C_1 C_2}} = 10\\text{ Hz}',
        explanation: 'Cutoff frequency of 2nd-order Sallen-Key low-pass filter to eliminate 50/60 Hz noise.',
      },
      {
        formula: 'V_{\\text{out}} = V_{\\text{offset}} + G \\cdot (V_{\\text{in}} - V_{\\text{ref}})',
        explanation: 'Level shifting equation mapping biological potential to the unipolar 0-3.3V ESP32 ADC range.',
      },
    ],
    componentsList: [
      { ref: 'U1 (A/B)', value: 'LTC2050HV / AD8605', desc: 'Dual Zero-Drift, Rail-to-Rail, pA-range bias op-amp', package: 'MSOP-8 / SOIC-8' },
      { ref: 'R_SOURCE', value: '100 MΩ (Sensor model)', desc: 'Electrode high internal source resistance', package: 'Sensor model' },
      { ref: 'R1, R2', value: '160 kΩ (0.1%)', desc: 'Sallen-Key precision metal film resistors', package: 'SMD 0603' },
      { ref: 'C1', value: '140 nF (5% C0G/film)', desc: 'Sallen-Key feedback capacitor', package: 'SMD 0805' },
      { ref: 'C2', value: '70 nF (5% C0G/film)', desc: 'Sallen-Key ground shunt capacitor', package: 'SMD 0805' },
      { ref: 'D_ESD', value: 'BAV199', desc: 'Low-leakage (<5pA) dual ESD protection diode', package: 'SOT-23' },
    ],
    simulationData: {
      ...generateTransient(100, (t) => {
        // Step in pH at t=0.04s + noise
        const inputBase = t < 0.04 ? 0.05 : -0.08; // mV scale
        const noise = 0.02 * Math.sin(2 * Math.PI * 50 * t);
        const vin = inputBase + noise;
        // Filtered and amplified output: baseline 1.65V, swings up for infection
        const vout = 1.65 - (inputBase * 10) * (1 - Math.exp(-t / 0.015));
        return { vin, vout };
      }),
      ...generateBode(10, 2, 14),
    },
  },
  {
    id: 'moisture_afe',
    title: '2. Wound Moisture / Bio-Impedance Exudate Circuit',
    subsystem: 'AC Impedance Spectroscopy & Exudate Conductance Interface',
    description:
      'AC-excited bio-impedance measurement circuit using interdigitated microelectrodes (IDE). An on-board 10 kHz low-distortion sine/square wave oscillator prevents electrode polarization and electrochemical corrosion, coupled to an instrumentation amplifier and precision synchronous envelope detector.',
    principle:
      'Applying direct DC voltage across moist biological tissue causes silver ion migration, electrode polarization, and cell damage. This AFE uses a symmetrical 10 kHz AC carrier wave (V_exc = 200 mVpp). As localized inflammation and exudate accumulation occur, the tissue impedance drops from ~50 kΩ (dry/scab) down to <1.2 kΩ (heavy exudate).',
    keySpecs: [
      'Excitation Frequency: 10.0 kHz (safe non-polarizing AC carrier)',
      'Excitation Amplitude: 200 mV_pp (well below 700 mV water hydrolysis window)',
      'Impedance Dynamic Range: 500 Ω (saturated exudate) to 100 kΩ (dry wound bed)',
      'Demodulation: Precision Full-Wave Active Rectifier + 3rd-order Butterworth LPF',
      'Electrode Configuration: Interdigitated Array (IDA) gold/polyimide with 200 μm finger spacing',
      'Response Time: < 50 ms for continuous wetness detection',
    ],
    schematicSvgType: 'moisture',
    netlistCir: `* HealSecure AI - Wound Moisture Bio-Impedance AFE
* SPICE Netlist for LTspice
.SUBCKT HEALSECURE_MOISTURE_AFE VDD VSS V_EXC_IN V_BIO_OUT

* 10kHz AC Excitation Oscillator (Wien Bridge / CMOS)
V_AC_EXC V_EXC_IN 0 SINE(0 0.1 10000)

* Bio-Impedance Wound Model (Cole-Cole R_exudate || C_tissue)
* Dry = 50k, Wet/Infected = 1.5k
R_LIMIT V_EXC_IN N_TISSUE_TOP 10k
R_EXUDATE N_TISSUE_TOP 0 2.2k
C_TISSUE N_TISSUE_TOP 0 10n

* AC Coupled Precision Instrumentation Stage (AD8220)
C_BLOCK N_TISSUE_TOP N_AMP_IN 100n
R_BIAS N_AMP_IN 0 1MEG
X_U2 N_AMP_IN 0 V_AMP_OUT VDD VSS AD8220

* Active Precision Full-Wave Rectifier
R_IN V_AMP_OUT N_INV_IN 10k
R_FWD N_INV_IN N_DIODE 10k
D1 N_INV_IN N_DIODE 1N4148
D2 N_DIODE N_RECT_OUT 1N4148

* Low-Pass Smoothing Filter (Envelope Detector fc = 50Hz)
R_SMOOTH N_RECT_OUT V_BIO_OUT 47k
C_SMOOTH V_BIO_OUT 0 1u

.ENDS HEALSECURE_MOISTURE_AFE

V1 VDD 0 3.3
V2 VSS 0 0
X_AFE VDD VSS V_EXC_IN V_BIO_OUT HEALSECURE_MOISTURE_AFE
.tran 0 0.01 0 100n
.plot V(V_BIO_OUT)
.end`,
    ltspiceAsc: `Version 4
SHEET 1 1280 920
WIRE 140 180 80 180
WIRE 280 180 200 180
WIRE 420 180 340 180
FLAG 80 240 0
FLAG 420 240 0
FLAG 80 180 V_EXC
FLAG 960 180 V_MOISTURE_OUT
TEXT 180 380 Left 2 !.tran 0 0.01 0 100n
TEXT 180 420 Left 2 ; HealSecure AI - Exudate Impedance AFE (10kHz AC Excitation)`,
    designEquations: [
      {
        formula: 'Z_{\\text{wound}}(\\omega) = R_{\\infty} + \\frac{R_0 - R_{\\infty}}{1 + (j\\omega \\tau)^\\alpha}',
        explanation: 'Cole-Cole biological tissue bio-impedance model describing exudate electrolyte conductance.',
      },
      {
        formula: 'V_{\\text{envelope}} = \\frac{2}{\\pi} \\cdot G \\cdot V_{\\text{exc}} \\cdot \\left(\\frac{Z_{\\text{exudate}}}{R_{\\text{ref}} + Z_{\\text{exudate}}}\\right)',
        explanation: 'Demodulated DC output voltage directly proportional to exudate ionic conductivity.',
      },
    ],
    componentsList: [
      { ref: 'U2', value: 'AD8220ARMZ / INA128', desc: 'JFET-input Rail-to-Rail precision instrumentation amplifier', package: 'MSOP-8' },
      { ref: 'U3', value: 'OPA2333', desc: 'Dual micro-power zero-drift op-amp for envelope detection', package: 'SOIC-8' },
      { ref: 'R_LIMIT', value: '10.0 kΩ (0.1%)', desc: 'Current-limiting series safety resistor (<20 μA current limit)', package: 'SMD 0603' },
      { ref: 'D1, D2', value: 'BAS16 / 1N4148W', desc: 'High-speed small-signal switching diodes', package: 'SOD-123' },
      { ref: 'C_SMOOTH', value: '1.0 μF (10V X7R)', desc: 'Envelope smoothing integration capacitor', package: 'SMD 0805' },
      { ref: 'IDE_SENSOR', value: 'Au-Interdigitated Array', desc: 'Biocompatible gold electrode on flexible polyimide substrate', package: 'Custom FPC' },
    ],
    simulationData: {
      ...generateTransient(100, (t) => {
        // 10kHz carrier modulated by exudate
        const carrier = Math.sin(2 * Math.PI * 10000 * t);
        const exudateResistanceFactor = t < 0.05 ? 0.3 : 0.85; // higher exudate wetness
        const vin = carrier * 0.1;
        const vout = 0.4 + exudateResistanceFactor * 2.2 * (1 - 0.05 * Math.sin(2 * Math.PI * 1000 * t));
        return { vin, vout };
      }),
      ...generateBode(50, 2, 20),
    },
  },
  {
    id: 'temp_bridge',
    title: '3. Differential Skin / Wound Temperature Hyperemia Bridge',
    subsystem: 'Dual-NTC Thermistor Differential Bridge (SSI Hyperemia Sentinel)',
    description:
      'Precision Wheatstone differential bridge measuring the temperature gradient (ΔT = T_wound - T_systemic) between the surgical site and healthy adjacent skin. Local hyperemia (ΔT > 1.2°C) is an early marker of localized inflammation modeled before systemic deterioration.',
    principle:
      'Two matched 10k NTC thermistors (B = 3950K) are arranged in opposing arms of a Wheatstone bridge driven by a low-drift 2.50V voltage reference (LM4040). INA333 instrumentation amplifier; gain and temperature-gradient sensitivity require calibration.',
    keySpecs: [
      'Bridge Excitation: 2.500 V precision reference (LM4040-2.5, 20 ppm/°C drift)',
      'Thermistor Type: Dual matched 10 kΩ @ 25°C NTC (B25/85 = 3950K, ±0.1°C interchangeability)',
      'Gain Resistor: RG = 1.00 kΩ (Sets INA333 differential gain G = 1 + 100k/RG = 101)',
      'Measurement Range: ΔT = -2.0°C to +6.0°C (Output: 0.2V to 3.0V)',
      'Hyperemia Alarm Threshold: ΔT ≥ +1.20°C (indicative of acute inflammatory vasodilation)',
      'Common Mode Rejection Ratio (CMRR): > 100 dB (eliminates ambient baseline drift)',
    ],
    schematicSvgType: 'temp',
    netlistCir: `* HealSecure AI - Differential Wound Hyperemia Bridge AFE
* SPICE Netlist for LTspice
.SUBCKT HEALSECURE_TEMP_BRIDGE VDD VSS V_REF_2V5 V_DELTA_OUT

* Precision 2.5V Voltage Reference
X_REF VDD V_REF_2V5 LM4040_2V5

* Wheatstone Bridge Arms
* Left Arm: Fixed R1 (10k) + NTC_Wound (10k at baseline)
R1 V_REF_2V5 N_WOUND_DIV 10k
R_NTC_WOUND N_WOUND_DIV 0 9.2k ; Lower R due to infection hyperemia (higher temp)

* Right Arm: Fixed R2 (10k) + NTC_Systemic_Ref (10k at 37C)
R2 V_REF_2V5 N_SYS_DIV 10k
R_NTC_SYS N_SYS_DIV 0 10.0k

* INA333 Micro-Power Rail-to-Rail Instrumentation Amplifier
* RG = 1k gives Gain = 1 + 100k/1k = 101
RG N_RG1 N_RG2 1.00k
X_INA333 N_SYS_DIV N_WOUND_DIV N_RG1 N_RG2 V_DELTA_OUT 0 VDD VSS INA333

* 100nF RFI/EMI bypass filter capacitors
C_RF1 N_WOUND_DIV 0 10n
C_RF2 N_SYS_DIV 0 10n
C_DIF N_WOUND_DIV N_SYS_DIV 100n

.ENDS HEALSECURE_TEMP_BRIDGE

V_SUPPLY VDD 0 3.3
V_GND VSS 0 0
X1 VDD VSS V_REF V_DELTA_OUT HEALSECURE_TEMP_BRIDGE
.op
.tran 0 0.05 0 10u
.plot V(V_DELTA_OUT)
.end`,
    ltspiceAsc: `Version 4
SHEET 1 1280 920
WIRE 200 120 140 120
WIRE 320 120 200 120
WIRE 200 240 200 180
WIRE 320 240 320 180
FLAG 200 360 0
FLAG 320 360 0
FLAG 140 120 V_REF_2V5
FLAG 780 240 V_DELTA_OUT
SYMBOL res 180 120 R0
SYMATTR InstName R1_10k
SYMATTR Value 10k
SYMBOL res 300 120 R0
SYMATTR InstName R2_10k
SYMATTR Value 10k
SYMBOL res 180 240 R0
SYMATTR InstName NTC_WOUND
SYMATTR Value 9.2k
SYMBOL res 300 240 R0
SYMATTR InstName NTC_SYSTEMIC
SYMATTR Value 10.0k
SYMBOL Opamps\\\\INA333 560 220 R0
SYMATTR InstName U4_INA333
SYMATTR Value INA333
TEXT 180 420 Left 2 !.op
TEXT 180 460 Left 2 ; HealSecure AI - Differential Wound Hyperemia Bridge (INA333 Gain=101)`,
    designEquations: [
      {
        formula: 'R(T) = R_0 \\cdot \\exp\\left[\\beta \\cdot \\left(\\frac{1}{T} - \\frac{1}{T_0}\\right)\\right]',
        explanation: 'Steinhart-Hart exponential NTC thermistor resistance versus temperature curve.',
      },
      {
        formula: '\\Delta V_{\\text{bridge}} = V_{\\text{ref}} \\cdot \\left( \\frac{R_{\\text{wound}}}{R_1 + R_{\\text{wound}}} - \\frac{R_{\\text{sys}}}{R_2 + R_{\\text{sys}}} \\right)',
        explanation: 'Wheatstone differential output voltage responding strictly to localized thermal difference.',
      },
      {
        formula: 'V_{\\text{out}} = V_{\\text{ref\\_offset}} + \\left(1 + \\frac{100\\text{ k}\\Omega}{R_G}\\right) \\cdot \\Delta V_{\\text{bridge}}',
        explanation: 'Transfer function of INA333 instrumentation amplifier with gain set by RG.',
      },
    ],
    componentsList: [
      { ref: 'U4', value: 'INA333AIDGKR', desc: 'Precision Micro-Power, Rail-to-Rail Instrumentation Amp (Vos < 25μV)', package: 'VSSOP-8' },
      { ref: 'U5', value: 'LM4040AIM3-2.5', desc: 'Precision 2.500V micropower shunt voltage reference (0.1% tolerance)', package: 'SOT-23' },
      { ref: 'NTC1', value: 'NTC 10k (B=3950K)', desc: 'Miniature flexible NTC bead (proposed prototype wound site sensor)', package: 'Epoxy bead / 0402' },
      { ref: 'NTC2', value: 'NTC 10k (B=3950K)', desc: 'Reference skin temperature sensor (Systemic reference)', package: 'Epoxy bead / 0402' },
      { ref: 'R1, R2', value: '10.00 kΩ (0.05%)', desc: 'Ultra-low TCR (5 ppm/°C) precision thin film bridge resistors', package: 'SMD 0603' },
      { ref: 'RG', value: '1.00 kΩ (0.1%)', desc: 'INA333 Gain setting resistor (Gain = 101)', package: 'SMD 0603' },
    ],
    simulationData: {
      ...generateTransient(100, (t) => {
        // Hyperemia thermal step
        const deltaT = t < 0.03 ? 0.2 : 1.85; // C
        const vin = (deltaT / 10) * 0.05;
        const vout = 0.5 + deltaT * 0.45 * (1 - Math.exp(-t / 0.01));
        return { vin, vout };
      }),
      ...generateBode(5, 1, 40),
    },
  },
  {
    id: 'ppg_afe',
    title: '4. Optical PPG Pulse Oximeter AFE (Discrete Reference / Alternative Design)',
    subsystem: 'Discrete Photoplethysmography TIA & Bandpass Conditioner (Alternative to Primary MAX30102 I2C)',
    description:
      'Discrete dual-wavelength optical transimpedance amplifier (TIA) reference front-end with ambient optical cancellation and active 0.5–5.0 Hz bandpass filtering. (Note: The primary physical prototype uses the integrated I2C MAX30102 module for board compactness; this discrete schematic serves as the open-hardware analog reference design for deep SPICE simulation and custom silicon roadmap).',
    principle:
      'In the primary HealSecure prototype patch, digital optical sensing is handled via the integrated MAX30102 (I2C) to minimize flexible PCB trace count and eliminate analog noise pickup. This discrete circuit models the underlying transimpedance physics: Red (660 nm) and Infrared (940 nm) photocurrents from a discrete Si PIN photodiode are converted to voltage via an ultra-low-noise op-amp (OPA2388 / AD8606) with active baseline servo cancellation, followed by Sallen-Key bandpass filtering.',
    keySpecs: [
      'Primary Prototype Path: Integrated MAX30102 I2C sensor (digital output directly to ESP32)',
      'Discrete Reference Architecture: Si PIN Photodiode (0.5 mm² active area, peak 650-950 nm)',
      'Transimpedance Gain: R_TIA = 1.0 MΩ (yielding 1.0 V per microampere of photocurrent)',
      'Bandpass Corner Frequencies: High-pass fc1 = 0.5 Hz (30 bpm), Low-pass fc2 = 5.0 Hz (300 bpm)',
      'Total AC Voltage Gain: 46 dB (200x amplification of pulsatile AC arterial wave)',
      'Ambient Light Cancellation: Active current-subtraction integrator (rejection up to 100 μA DC)',
    ],
    schematicSvgType: 'ppg',
    netlistCir: `* HealSecure AI - Photoplethysmography (PPG) Pulse Oximetry AFE
* SPICE Netlist for LTspice
.SUBCKT HEALSECURE_PPG_AFE VDD VSS I_PD_IN V_PPG_AC_OUT

* Photodiode Model: DC photocurrent (1.5uA) + AC arterial pulse (40nA peak) at 2.2Hz (132 bpm)
I_PD 0 N_PD_CATHODE SINE(1.5u 40n 2.2)

* Transimpedance Amplifier (TIA Stage - OPA388 / AD8605)
R_TIA N_PD_CATHODE N_TIA_OUT 1MEG
C_TIA N_PD_CATHODE N_TIA_OUT 3.3p ; Stability feedback capacitor
X_U5A 0 N_PD_CATHODE N_TIA_OUT VDD VSS OPA388

* AC-Coupled High-Pass Filter (fc = 0.5Hz, blocks venous DC & ambient)
C_HP1 N_TIA_OUT N_HP_NODE 3.3u
R_HP1 N_HP_NODE 1.65 100k

* 2nd-Order Sallen-Key Low-Pass Filter (fc = 5Hz)
R_LP1 N_HP_NODE N_SK_MID 33k
R_LP2 N_SK_MID N_LP_IN 33k
C_SK1 N_SK_MID V_PPG_AC_OUT 1.5u
C_SK2 N_LP_IN 0 680n
X_U5B N_LP_IN V_PPG_AC_OUT V_PPG_AC_OUT VDD VSS OPA388

.ENDS HEALSECURE_PPG_AFE

V_CC VDD 0 3.3
V_EE VSS 0 0
X_PPG VDD VSS I_IN V_PPG_AC_OUT HEALSECURE_PPG_AFE
.tran 0 2 0 1m
.plot V(V_PPG_AC_OUT)
.end`,
    ltspiceAsc: `Version 4
SHEET 1 1280 920
WIRE 140 180 80 180
WIRE 280 180 200 180
WIRE 420 180 340 180
FLAG 80 260 0
FLAG 860 180 V_PPG_AC_OUT
FLAG 80 180 I_PD_IN
SYMBOL current 80 220 R0
SYMATTR InstName I_PD
SYMATTR Value SINE(1.5u 40n 2.2)
SYMBOL res 260 120 R90
SYMATTR InstName R_TIA
SYMATTR Value 1MEG
SYMBOL cap 260 80 R90
SYMATTR InstName C_TIA
SYMATTR Value 3.3p
SYMBOL Opamps\\\\OPA388 340 200 R0
SYMATTR InstName U5A_TIA
SYMATTR Value OPA388
TEXT 160 420 Left 2 !.tran 0 2 0 1m
TEXT 160 460 Left 2 ; HealSecure AI - Pulse Oximeter PPG Front-End (TIA + 0.5-5Hz Bandpass)`,
    designEquations: [
      {
        formula: 'V_{\\text{TIA}} = -I_{\\text{photo}} \\cdot R_{\\text{TIA}} = - (I_{\\text{DC}} + I_{\\text{AC}}) \\cdot 1.0\\text{ M}\\Omega',
        explanation: 'Current-to-voltage transimpedance conversion with high dynamic range.',
      },
      {
        formula: 'f_{L} = \\frac{1}{2\\pi R_{HP} C_{HP}} = 0.48\\text{ Hz}, \\quad f_{H} = \\frac{1}{2\\pi \\sqrt{R_1 R_2 C_1 C_2}} = 5.0\\text{ Hz}',
        explanation: 'Cardiovascular bandpass filter passband window isolating heart rates from 30 to 300 bpm.',
      },
      {
        formula: 'R = \\frac{(AC/DC)_{660\\text{ nm}}}{(AC/DC)_{940\\text{ nm}}}, \\quad \\text{SpO}_2 \\approx 110 - 25 \\cdot R',
        explanation: 'Standard empirical calibration curve for dual-wavelength pulse oximetry ratio-of-ratios (R).',
      },
    ],
    componentsList: [
      { ref: 'U5 (A/B)', value: 'OPA2388 / AD8606', desc: 'Precision Zero-Drift, Low-Noise, Rail-to-Rail Dual Op-Amp', package: 'VSSOP-8' },
      { ref: 'D_PD', value: 'TEMD5010X01', desc: 'High-speed silicon PIN photodiode (7.5 mm² sensitive area, 60° angle)', package: 'SMD flat top' },
      { ref: 'LED_DUAL', value: 'DCM-03', desc: 'Bi-color Red (660nm) & Infrared (940nm) high-radiance medical LED', package: 'SMD package' },
      { ref: 'R_TIA', value: '1.00 MΩ (0.1%)', desc: 'Precision low-noise thin film transimpedance feedback resistor', package: 'SMD 0805' },
      { ref: 'C_TIA', value: '3.3 pF (C0G)', desc: 'Stability phase-lead compensation capacitor (prevents TIA oscillation)', package: 'SMD 0603' },
      { ref: 'C_HP', value: '3.3 μF (Tantalum/X7R)', desc: 'AC coupling capacitor for baseline wander removal', package: 'SMD 0805' },
    ],
    simulationData: {
      ...generateTransient(100, (t) => {
        // Arterial pulsatile PPG waveform with dicrotic notch
        const phase = 2 * Math.PI * 2.2 * t;
        const systolic = Math.sin(phase);
        const dicrotic = 0.35 * Math.sin(2 * phase + 0.6);
        const vin = 0.001 * (systolic + dicrotic);
        const vout = 1.65 + 0.85 * (systolic + dicrotic) * (systolic > -0.2 ? 1 : 0.6);
        return { vin, vout };
      }),
      ...generateBode(2.2, 2, 46),
    },
  },
];
